### ISSUE TITLE
testing out the 3.16rc2 branch

### ISSUE THREAD

**Issue by jcftang** [xobs/novena-linux#1]
been testing out the 3.16rc2 branch, getting these errors on boot

<pre>
[    5.641325] asix 1-1.2:1.0 eth2: register 'asix' at usb-ci_hdrc.1-1.2, ASIX AX88772B USB 2.0 Ethernet, 00:0e:c6:87:72:01
[    5.653213] it6251 2-005c: Error -5 reading from subaddress 0x0
[    5.659537] it6251 2-005c: Error -5 reading from subaddress 0x1
[    5.665920] it6251 2-005c: Error -5 reading from subaddress 0x2
[    5.672318] it6251 2-005c: Error -5 reading from subaddress 0x3
[    5.678265] it6251 2-005c: unable to read product id, deferring
[    5.684433] i2c 2-005c: Driver it6251 requests probe deferral
</pre>

I haven't copied in the kernel modules to my base image yet, i would have expected most things to be statically linked into the kernel.

**Comment by jcftang** [comment]
I guess I dont have the edt adapter board so thats failing for me

**Comment by xobs** [comment]
The very last line of the bootloader script runs the following command:

fdt addr 0x11ff0000; run prep_gbit; run prep_pcie; run prep_senoko; run prep_es8328; run prep_retina; run prep_pixelqi; run prep_hdmi

The various scripts prep_\* are generated by U-Boot in board/kosagi/novena/peripherals.c and work by consulting the EEPROM for various enabled feature flags.  Currently-deployed installations use V1 of the EEPROM data.

Your board must have the "retina" flag enabled.  Therefore, it is indicating to Linux that there should be an IT6251 hanging out on /dev/i2c-2.  The "correct" way to fix it is to get novena-eeprom and remove that flag.  novena-eeprom is in Debian Jessie, or is available from my git repo.

**Comment by jcftang** [comment]
FYI, on the board that I have...

root@novena:~# ./novena-eeprom 
Current EEPROM settings:
    Signature:   Novena
    Version:     1
    Serial:      19
    MAC:         00:1f:11:02:15:12
    Features:    0x71 (es8328,pcie,gbit,hdmi)

**Comment by xobs** [comment]
In that case, since your flags are correct, the problem probably lies in the way devices are enabled/disabled.  It used to be that dts files contained 'status="disabled"', but this was changed to read 'status="okay"'.  In the past, U-Boot "turned on" features, but now we need to "turn them off".

U-Boot will need to be patched to delete device tree nodes when features are not present.  This should be fixed when we rework the boot process, sometime after Senoko rework has been completed.

**Comment by xobs** [comment]
U-Boot has been patched now to take care of this situation.  Things should be working better now!

**Comment by jcftang** [comment]
Tested and verified, it works me me on my end -- others should test if they can!
