### ISSUE TITLE
make deb-pkg fails on the 3.16rc2 branch

### ISSUE THREAD

**Issue by jcftang** [xobs/novena-linux#2]
Trying this out

```
make uImage LOADADDR=10008000 -j 4 deb-pkg
```

and I get this...

<pre>
  CC [M]  drivers/usb/serial/symbolserial.o
In file included from include/linux/byteorder/little_endian.h:4:0,
                 from ./arch/arm/include/uapi/asm/byteorder.h:21,
                 from include/asm-generic/bitops/le.h:5,
                 from ./arch/arm/include/asm/bitops.h:340,
                 from include/linux/bitops.h:33,
                 from include/linux/kernel.h:10,
                 from drivers/usb/serial/symbolserial.c:13:
include/uapi/linux/byteorder/little_endian.h:43:1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
  CC [M]  drivers/usb/serial/usb_wwan.o
  CC [M]  net/ipv6/ipcomp6.o
  CC [M]  drivers/usb/serial/ti_usb_3410_5052.o
The bug is not reproducible, so it is likely a hardware or OS problem.
make[5]: *** [drivers/usb/serial/symbolserial.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC [M]  net/ipv6/xfrm6_tunnel.o
  CC [M]  net/ipv6/tunnel6.o
  CC [M]  net/ipv6/xfrm6_mode_transport.o
  CC [M]  net/ipv6/xfrm6_mode_tunnel.o
make[4]: *** [drivers/usb/serial] Error 2
make[3]: *** [drivers/usb] Error 2
make[2]: *** [drivers] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC [M]  net/ipv6/xfrm6_mode_beet.o
  CC [M]  net/ipv6/mip6.o
  CC [M]  net/ipv6/sit.o
  CC [M]  net/ipv6/ip6_tunnel.o
  LD [M]  net/ipv6/ipv6.o
make[2]: *** [net] Error 2
make[1]: *** [deb-pkg] Error 2
make: *** [deb-pkg] Error 2
[jtang@novena-ie-1 novena-linux (v3.16-rc2-novena)]$ 
</pre>

**Comment by jcftang** [comment]
Oops, closing this now. Turns I didn't do this...

<pre>
#!/bin/sh
make -j4 \
        LOADADDR=0x10008000 \
        LD=gold \
        KBUILD_DEBARCH=armhf \
        KBUILD_IMAGE=uImage \
        KBUILD_DTB=imx6q-novena.dtb \
        LOCALVERSION=-novena \
        KDEB_PKGVERSION=1.2 \
        EMAIL="xobs@kosagi.com" \
        NAME="Sean Cross" \
        imx6q-novena.dtb || exit 1
make -j4 \
        LOADADDR=0x10008000 \
        LD=gold \
        KBUILD_DEBARCH=armhf \
        KBUILD_IMAGE=uImage \
        KBUILD_DTB=imx6q-novena.dtb \
        LOCALVERSION=-novena \
        KDEB_PKGVERSION=1.2 \
        EMAIL="xobs@kosagi.com" \
        NAME="Sean Cross" \
        deb-pkg
</pre>

**Comment by xobs** [comment]
That looks like a problem with undervolting the CPU.  Does your boot.scr contain the line "i2c mw 08 20 26"?  If so, your CPU is running at 1.2V, well south of the 1.375V recommended for 1.2 GHz operation.

**Comment by jcftang** [comment]
Yea, it contains that line. I lifted it from ...https://raw.githubusercontent.com/sutajiokousagi/meta-kosagi/novena/recipes-bsp/u-boot/u-boot-imx/boot.script as per instructions from http://www.kosagi.com/w/index.php?title=Novena/DebianBuildProcess#Compile_the_u-boot_boot_script. They might just need to be updated.

**Comment by xobs** [comment]
Thanks for finding that.  I've updated the boot.script file to reflect
the new best-practices.

Note that the boot script is assuming you're booting to /dev/mmcblk0p2. 
Our systems have SATA disks, with partition 2 used as an 8GB swap
partition.  Therefore, for our systems we replace "root=/dev/mmcblk0p2"
with "root=/dev/sda3 resume=/dev/sda2" for the non-recovery bootargs.

**Comment by jcftang** [comment]
Ok, that was pretty obvious from looking at the script, is sda1 just a reserved partition for now?

**Comment by xobs** [comment]
Yes, sda1 is reserved.

The i.MX6 supports booting from SATA, so in theory if you short the SATA
header you can do away with the MMC card entirely.  If you do this,
you'll want sda1 to be present, and formatted FAT.  We've gotten this
working in the past, once, but haven't really pursued it.
